### PR TITLE
Update latest WP version from 4.1 to 4.2

### PR DESCRIPTION
**Pull request by sc0ttkclark**

### CODE REVIEW

**Comment by tlovett1** [comment]
@ericmann is this all we need or do we need something for composer?

**Comment by johnpbloch** [comment]
It might be worth using the WP.org API to fetch the current latest version [like the import command does](https://github.com/10up/Derrick-CLI/blob/master/lib/commands/import.js#L215) instead of needing to update the version with every point release.

**Comment by sc0ttkclark** [comment]
VV uses latest always by default, letting you specify version only if necessary https://github.com/bradp/vv/blob/master/vv#L530

**Comment by ericmann** [comment]
I like the idea, but since latest is 4.2.1 and not 4.2, this won't necessarily fix the issue today either. If no WP version is specified in the manifest file, Composer pulls in the latest version on import anyway. We need to update the create command to accept "latest" or blank for the WP version so it creates a manifest that auto-imports the latest version.

My hesitation here is running create on one day, then moving forward with, say, 4.2 happily (but without anything in the manifest), then shipping the manifest to a team member after 4.3 is out. We'll end up with a different (potentially breaking) between dev environments that can and should be avoided.

So I'm thinking create should allow "latest" or no entry for WP version, and should use the .org API to get the _current_ version and hard-code that into the manifest so we have stability. Open to hearing other opinions, though.

**Pull request closed without merging**
